# Generated by Django 3.1.3 on 2021-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('About Us', 'About Us'), ('Self-Care', 'Self-Care')], default='uncategorized', max_length=255),
        ),
    ]
