# Generated by Django 3.1.3 on 2021-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210108_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('About Us', 'About Us'), ('Self Care', 'Self Care'), ('Hy-phen', 'Hy-phen')], default='uncategorized', max_length=255),
        ),
    ]
