# Generated by Django 4.0.5 on 2022-08-06 19:49

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogauthor_blogauthorsorderable_blogcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('block_quote', wagtail.blocks.BlockQuoteBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())], use_json_field=None),
        ),
    ]
