# Generated by Django 4.0.5 on 2022-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_aboutindexpage_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='phone',
            field=models.CharField(default='913-257-5808', max_length=10),
        ),
    ]
