# Generated by Django 4.0.5 on 2022-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogcategory_slug_alter_aboutpage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='test', help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
        ),
    ]
