# Generated by Django 4.0.5 on 2022-08-14 07:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='name',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='awards',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=None),
        ),
    ]
