# Generated by Django 4.0.5 on 2022-08-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_aboutpage_name_alter_aboutpage_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutIndexPage',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
