# Generated by Django 3.1.3 on 2021-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinformation',
            name='signature',
            field=models.FileField(default='ABC', upload_to=''),
        ),
    ]
