# Generated by Django 3.1.3 on 2021-01-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0002_practiceinformation_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceinformation',
            name='signature',
        ),
        migrations.AddField(
            model_name='practiceinformation',
            name='SigdataURL',
            field=models.TextField(default='ABC'),
        ),
    ]
