# Generated by Django 4.0.5 on 2022-08-15 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0003_aboutpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='phone',
            field=models.CharField(blank=True, default='913-257-5808', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'. Up to 12 digits allowed.", regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
