# Generated by Django 4.0.5 on 2022-08-15 06:32

import django.core.validators
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0004_alter_aboutpage_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='awards',
            new_name='other',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='phone',
            field=models.CharField(blank=True, default='913-257-5808', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'. Up to 12 digits allowed.", regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
