# Generated by Django 3.1.3 on 2021-01-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0005_auto_20210108_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationpolicyinformation',
            name='sig_data_URL',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancellationpolicyinformation',
            name='sig_img',
            field=models.ImageField(blank=True, upload_to='sig_images/cancellation_policy_form_sigs'),
        ),
        migrations.AddField(
            model_name='paymentpolicyinformation',
            name='sig_data_URL',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentpolicyinformation',
            name='sig_img',
            field=models.ImageField(blank=True, upload_to='sig_images/payment_policy_form_sigs'),
        ),
        migrations.AddField(
            model_name='releaseofinformation',
            name='sig_data_URL',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='releaseofinformation',
            name='sig_img',
            field=models.ImageField(blank=True, upload_to='sig_images/roi_form_sigs'),
        ),
        migrations.AlterField(
            model_name='practiceinformation',
            name='sig_img',
            field=models.ImageField(blank=True, upload_to='sig_images/practice_form_sigs'),
        ),
    ]
