# Generated by Django 3.1.3 on 2021-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0006_auto_20210111_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinformation',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
