# Generated by Django 3.1.3 on 2021-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0007_practiceinformation_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationpolicyinformation',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentpolicyinformation',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='releaseofinformation',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
