# Generated by Django 3.1.3 on 2021-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0008_auto_20210112_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeAndSoundInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('parent_first_name', models.CharField(max_length=100, verbose_name='Parent/legal guardian first name')),
                ('parent_last_name', models.CharField(max_length=100, verbose_name='Parent/legal guardian last name')),
                ('ss_other', models.CharField(blank=True, max_length=200, null=True)),
                ('ss_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('gs_other', models.CharField(blank=True, max_length=200, null=True)),
                ('gs_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('completed_ssp', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('completed_ssp_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('prior_listen_ther', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('prior_listen_ther_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('how_music_affect_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('symp_other', models.CharField(blank=True, max_length=200, null=True)),
                ('dv_other', models.CharField(blank=True, max_length=200, null=True)),
                ('home_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('for_children', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('for_children_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('for_adults', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('for_adults_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('quiet_space', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('quiet_space_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('peaceful_env', models.CharField(blank=True, choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('peaceful_env_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('life_comfy_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('willingness_comm', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
    ]
