# Generated by Django 3.1.3 on 2021-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0009_safeandsoundinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent/legal guardian first name'),
        ),
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent/legal guardian last name'),
        ),
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='ss_comm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
