# Generated by Django 3.1.3 on 2021-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedcon_main', '0011_auto_20210115_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DorsalVagal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundSensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sympathetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='safeandsoundinformation',
            name='ss_comm',
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='general_feeling_home',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Calm', '1 - Calm'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Chaotic', '10 - Chaotic')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='how_music_affect',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Calming, Grounding', '1 - Calming, Grounding'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Aggravating, Irritating', '10 - Aggravating, Irritating')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='life_comfy',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Comfortable', '1 - Comfortable'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Unsettled', '10 - Unsettled')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='noise',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Peaceful, Quiet', '1 - Peaceful, Quiet'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Frenzied, Loud', '10 - Frenzied, Loud')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='people_in_home',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Supportive', '1 - Supportive'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Unpredictable', '10 - Unpredictable')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='reaction_to_stress',
            field=models.CharField(choices=[('', 'Select...'), ('1 - Sympathetic hyper-arousal (activation/mobilization)', '1 - Sympathetic hyper-arousal (activation/mobilization)'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 - Dorsal vagal hypo-arousal (shutdown/immobilization)', '10 - Dorsal vagal hypo-arousal (shutdown/immobilization)')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='willingness',
            field=models.CharField(choices=[('', 'Select...'), ("1 - I'm all in", "1 - I'm all in"), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ("10 - I'm skeptical", "10 - I'm skeptical")], default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='peaceful_env',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='prior_listen_ther',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='safeandsoundinformation',
            name='quiet_space',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='dorsal_vagal',
            field=models.ManyToManyField(to='pedcon_main.DorsalVagal'),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='general_sensitivity',
            field=models.ManyToManyField(to='pedcon_main.GeneralSensitivity'),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='sound_sensitivity',
            field=models.ManyToManyField(to='pedcon_main.SoundSensitivity'),
        ),
        migrations.AddField(
            model_name='safeandsoundinformation',
            name='sympathetic',
            field=models.ManyToManyField(to='pedcon_main.Sympathetic'),
        ),
    ]
